# Configuration for Create Issue Upon Repo Creation


# Enables the creation of an issue when a new repository is created
enableIssueCreation: true

# Issue Title when a repository is created
createdIssueTitle: 'Repository Setup First Steps'

# Issue Body when a repository is created
createdIssueBody: 'Congratulations! You\'ve just created a new repository. Please complete the following tasks to make sure that your work can be seen and discoverable by other members of the organization:\n- [ ] Give @[xgizzo]/[xteam] at least read access\n- [ ] Add some [topics](https://blog.github.com/2017-01-31-introducing-topics/) that describe the content and purpose of your repository'

# Users/Groups that should be cc'ed on the issue. Should be users/groups separated by a space.
# ccList: '@user123 @user456'
