name: Enforce repository settings

on: [push]

jobs:
  probot-settings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run settings
      uses: elstudio/actions-settings@v2
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_SETTINGS}}
